# definindo banco de dados H2 no modo Mysql que é o que usamos em producao
datasources:
  default:
    url: jdbc:h2:mem:testDb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver

#habilita log no contexto transacional
logger:
  levels:
    io.micronaut.transaction: DEBUG

#mostra de forma mais clara os comandos feitos ao banco de dados
jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: true
      hibernate.format_sql: true